name: Weather Bot (Persian Text)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  send-weather:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install requests arabic-reshaper python-bidi
      - name: Run weather bot
        env:
          RUBIKA_TOKEN: ${{ secrets.RUBIKA_TOKEN }}
        run: python weather_forecast.py
